/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs3354_hello_world;

import org.junit.jupiter.api.Test;

import cs3354_hello_world.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
